apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: client
          image: pkiposmet/yolo-client-server:1.1.0
          ports:
            - containerPort: 5001
        - name: backend
          image: pkiposmet/yolo-backend-server:1.0.0
          ports:
            - containerPort: 3000
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

