apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  selector:
    app: yolo
  ports:
    - name: frontend-port
      port: <frontend_port>
      targetPort: <frontend_port>
    - name: backend-port
      port: <backend_port>
      targetPort: <backend_port>
  type: LoadBalancer
